language: python

python:
  - "3.8"

env:
  global:
    KUBE_CONFIG=YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIHNlcnZlcjogaHR0cHM6Ly90c2FkaW1hcy5kbnMtY2xvdWQubmV0OjE2NDQzCiAgICBpbnNlY3VyZS1za2lwLXRscy12ZXJpZnk6IHRydWUKICBuYW1lOiBtaWNyb2s4cy1jbHVzdGVyCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBtaWNyb2s4cy1jbHVzdGVyCiAgICB1c2VyOiBhZG1pbgogIG5hbWU6IG1pY3JvazhzCmN1cnJlbnQtY29udGV4dDogbWljcm9rOHMKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBhZG1pbgogIHVzZXI6CiAgICBwYXNzd29yZDogVFZaSlFWbFhUblF3VWtoWFVFMUpTamxYU1VwMVRucG5kbk40T1RoSmVteDBlVEVyY1ZWU1R6bHdPRDBLCiAgICB1c2VybmFtZTogYWRtaW4K
    #     - REDIS_SERVER=localhost
    #    - REDIS_PASS=pass123
    #    - DB_HOST=localhost
    #    - DB_PORT=5432
    #    - DB_USER=postgres
    #    - DB_PASSWORD=pass123
    #    - DB_NAME=fadb

    #services:
    #- docker

before_install:
  - |
    cat <<EOL > .env
       REDIS_SERVER=localhost
       REDIS_PASS=pass123
       DB_HOST=localhost
       DB_PORT=5432
       DB_USER=postgres
       DB_PASSWORD=pass123
       DB_NAME=fadb
     EOL
     #- docker build -t tsadimas/myfastapi:db_ci .
     #- docker run --rm --net=host -d redis redis-server --requirepass pass123
     #- docker run --rm -e POSTGRES_PASSWORD=pass123 -e POSTGRES_DB=fadb -d --net=host -v pgdata:/var/lib/postgresql/data  postgres
     #- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode #> ${HOME}/.kube/config
  - | 
    cat <<EOL > ${HOME}/.kube/config
      apiVersion: v1
      clusters:
      - cluster:
          server: https://tsadimas.dns-cloud.net:16443
          insecure-skip-tls-verify: true
        name: microk8s-cluster
      contexts:
      - context:
          cluster: microk8s-cluster
          user: admin
        name: microk8s
      current-context: microk8s
      kind: Config
      preferences: {}
      users:
      - name: admin
        user:
          password: TVZJQVlXTnQwUkhXUE1JSjlXSUp1TnpndnN4OThJemx0eTErcVVSTzlwOD0K
          username: admin
    EOL
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

script:
  #- docker images tsadimas/myfastapi:db_ci
  #- docker run --net=host --env-file=.env tsadimas/myfastapi:db_ci pytest test_main.py
  - echo $(ls -l ~/.kube)
  - echo $(cat ~/.kube/config)
  - kubectl config view
    #- kubectl get pods
after_success:
  - echo "AFTER SUCCESS"
  #- if [ "$TRAVIS_BRANCH" == "ci" ] ; then
  #  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  #  docker push tsadimas/myfastapi:db_ci;
  #  fi

