sudo: required

language: python

python:
  - "3.8"

branches:
  only:
    - master
    - ci
env:
  global:
    - REDIS_SERVER=localhost
    - REDIS_PASS=pass123

services:
  - docker

before_install:
  - docker build -t tsadimas/myfastapi . 
  - docker run --rm --net=host -d redis redis-server --requirepass pass123
script:
  - docker run --net=host --env-file=.env tsadimas/myfastapi pytest test_main.py
 

