version: '3'
services:
  psql-db:
    image: 'postgres:11'
    volumes:
      - "fapgdata:/var/lib/postgresql/data"
      - "./psql_dump.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: pass123
  redis-server:
    image: 'redis'
    command: redis-server --requirepass pass123 --appendonly yes
    volumes:
      - ./redis-data:/data
  fastapi-app:
    restart: always
    build:
      context: .
      dockerfile: nonroot.Dockerfile

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: 
      - psql-db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.https.config:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi-app
volumes:
  fapgdata:
